### PR TITLE
feat: capacitor 5 support

### PR DESCRIPTION
**Pull request by AE1NS**
Closes https://github.com/diachedelic/capacitor-blob-writer/issues/59

### CODE REVIEW

**Comment by diachedelic** [comment]
Thanks. I have kept the iOS deployment target at 12.0 to support Capacitors v3 and v4.

**Comment by AE1NS** [comment]
Then I cant use this version. I cant build the app with target 12.0 when using capacitor 4+. I really dont understand why you not gonna release a 5.0.0 version which is just compatible with capacitor 5 (as I already mentioned in another ticket).

I really appreciate your work and dont want to be 'mad' here, but please understand that its inefficient for the users with the same problem as me (Build error - target must be 13) to publish this separatelly as custom version with a raised target.

**Comment by AE1NS** [comment]
grafik
Just installed the new released version. This is the error.

**Comment by diachedelic** [comment]
I don't get that error when building the demo, which uses Capacitor v5. What happens if you try to build it?

**Comment by AE1NS** [comment]
The build cancels with this error.

**Comment by diachedelic** [comment]
Why don't I get the error? I am using Xcode 14.3.

**Comment by AE1NS** [comment]
I dont have an answer to this.

This plugin is in my oppinion not compatible with capacitor 4+.

https://forum.ionicframework.com/t/upgrading-custom-plugins-from-capacitor-3-to-capacitor-4/231753

**Comment by diachedelic** [comment]
I would like to know whether your build environment is the exception, or mine. I would rather not maintain several version of this plugin unless absolutely necessary.

**Comment by AE1NS** [comment]
In my project.pbxproj I have set `IPHONEOS_DEPLOYMENT_TARGET = 13.0;` in the buildSettings.

**Comment by AE1NS** [comment]
Do you have the deployment target set?
https://stackoverflow.com/questions/49624300/does-ios-app-development-have-minimum-target-sdk-version-similar-to-androids

**Comment by diachedelic** [comment]
Yes, those are the values I see in the demo project.

**Comment by diachedelic** [comment]
You have tried building the demo app, right? It's here: https://github.com/diachedelic/capacitor-blob-writer/tree/master/demo.

**Comment by AE1NS** [comment]
No, just our project. Unfortunately if have currently not the possibility to test this.

**Comment by diachedelic** [comment]
I wonder how file-opener does it?

**Pull request closed without merging**
